version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      GO_ENV: PRODUCTION
      APP_SECRET: ${APP_SECRET}
      APP_ID: ${APP_ID}
      APP_TOKEN: ${APP_TOKEN}
